import { Router, type IRouter } from "express";
import {
  ListEpisodesQueryParams,
  GetEpisodeParams,
} from "@workspace/api-zod";
import { getFeedCached, getAutoGeneratedDescriptions, type RssEpisode } from "../lib/rss";
import { logger } from "../lib/logger";
import { getCuratedDescription } from "../lib/category-descriptions";
import { extractHistoryTimestamp } from "../lib/history-detection";
import { fetchAudioChapters, extractChapterHistoryTimestamp } from "../lib/id3-chapters";
import { sql, or, and, eq } from "drizzle-orm";
import { db, contentItemsTable, categoryDescriptionsTable } from "@workspace/db";
import {
  getEpisodeSeriesContext,
  libraryRowToRssEpisode,
} from "../lib/series";

const router: IRouter = Router();

const TAG_CACHE_TTL_MS = 5 * 60 * 1000;

type TagCacheEntry = {
  fetchedAt: number;
  items: EpisodeSummary[];
};

const tagQueryCache = new Map<string, TagCacheEntry>();

function tagCacheKey(normalizedTags: string[]): string {
  return [...normalizedTags].sort().join("|");
}

export function invalidateTagQueryCache(): void {
  tagQueryCache.clear();
  logger.info("Tag query cache invalidated");
}

function toEpisodeSummary(e: RssEpisode) {
  const { descriptionHtml: _unused, ...rest } = e;
  return rest;
}

router.get("/feed", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    res.json({
      title: feed.title,
      description: feed.description,
      link: feed.link,
      host: feed.host,
      artworkUrl: feed.artworkUrl,
      copyright: feed.copyright,
      language: feed.language,
      totalEpisodes: feed.totalEpisodes,
      latestPubDate: feed.latestPubDate,
      tipUrl: feed.tipUrl,
    });
  } catch (err) {
    logger.error({ err }, "Failed to load feed");
    res.status(502).json({ error: "Unable to load podcast feed" });
  }
});

type EpisodeSummary = Omit<RssEpisode, "descriptionHtml">;

router.get("/episodes", async (req, res) => {
  try {
    const rawTags = req.query["tags[]"] ?? req.query.tags;
    const tagsInput: string[] = Array.isArray(rawTags)
      ? (rawTags as string[])
      : typeof rawTags === "string"
        ? [rawTags]
        : [];

    const parsed = ListEpisodesQueryParams.safeParse({
      limit: req.query.limit != null ? Number(req.query.limit) : undefined,
      offset: req.query.offset != null ? Number(req.query.offset) : undefined,
      q: typeof req.query.q === "string" ? req.query.q : undefined,
      category:
        typeof req.query.category === "string" ? req.query.category : undefined,
      tags: tagsInput.length > 0 ? tagsInput : undefined,
    });
    if (!parsed.success) {
      res.status(400).json({ error: "Invalid query parameters" });
      return;
    }
    const { limit = 20, offset = 0, q, category, tags } = parsed.data;
    const feed = await getFeedCached();

    // Apply tag / category filter on RSS episodes, then strip descriptionHtml
    let rssItems = feed.episodes;
    if (tags && tags.length > 0) {
      const normalizedTags = tags.map((t) => t.toLowerCase());
      rssItems = rssItems.filter((e) =>
        e.categories.some((c) => normalizedTags.includes(c.toLowerCase())),
      );
    } else if (category) {
      const cat = category.toLowerCase();
      rssItems = rssItems.filter((e) =>
        e.categories.some((c) => c.toLowerCase() === cat),
      );
    }

    let items: EpisodeSummary[] = rssItems.map(toEpisodeSummary);

    // When a tags filter is active, also pull matching episodes from the full
    // DB library (3 800+ episodes) so historical content is included.
    // Results are cached in-memory for TAG_CACHE_TTL_MS to avoid repeated
    // heavy JSONB queries on every page change.
    if (tags && tags.length > 0) {
      const normalizedTags = tags.map((t) => t.toLowerCase());
      const cacheKey = tagCacheKey(normalizedTags);
      const now = Date.now();
      const cached = tagQueryCache.get(cacheKey);

      if (cached && now - cached.fetchedAt < TAG_CACHE_TTL_MS) {
        items = cached.items;
        logger.debug({ cacheKey }, "episodes: serving merged tag results from cache");
      } else {
        try {
          // Match any audio item whose `tags` OR `categories` JSONB column
          // contains at least one of the requested tag values.
          // Uses the proven `@>` containment operator (same as library.ts search).
          // One condition per tag, all OR'd together for both columns.
          const tagOrConditions = normalizedTags.flatMap((tag) => [
            sql`${contentItemsTable.tags} @> ${JSON.stringify([tag])}::jsonb`,
            sql`${contentItemsTable.categories} @> ${JSON.stringify([tag])}::jsonb`,
          ]);
          const dbRows = await db
            .select()
            .from(contentItemsTable)
            .where(
              and(
                sql`${contentItemsTable.kind} = 'audio'`,
                or(...tagOrConditions),
              ),
            )
            .orderBy(sql`${contentItemsTable.publishedAt} DESC`)
            .limit(2000);

          // Deduplicate against what RSS already returned
          const rssSlugSet = new Set(items.map((e) => e.slug));
          const rssEpNumSet = new Set(
            items
              .map((e) => e.episodeNumber)
              .filter((n): n is number => n != null),
          );

          for (const row of dbRows) {
            if (rssSlugSet.has(row.slug)) continue;
            if (row.episodeNumber != null && rssEpNumSet.has(row.episodeNumber))
              continue;

            items.push({
              slug: row.slug,
              guid: row.sourceId,
              episodeNumber: row.episodeNumber,
              title: row.title,
              link: row.link,
              pubDate: row.publishedAt.toISOString(),
              summary: row.summary,
              durationSeconds: row.durationSeconds,
              audioUrl: row.audioUrl,
              audioType: row.audioType,
              artworkUrl: row.artworkUrl,
              categories: row.categories,
            });
          }

          // Re-sort the merged list by most recent first
          items.sort((a, b) => b.pubDate.localeCompare(a.pubDate));

          tagQueryCache.set(cacheKey, { fetchedAt: now, items });
          logger.debug({ cacheKey, total: items.length }, "episodes: tag query result cached");
        } catch (dbErr) {
          logger.warn(
            { err: dbErr },
            "episodes: DB tags query failed, serving RSS-only results",
          );
        }
      }
    }

    if (q && q.trim()) {
      const needle = q.trim().toLowerCase();
      items = items.filter((e) => {
        return (
          e.title.toLowerCase().includes(needle) ||
          e.summary.toLowerCase().includes(needle) ||
          e.categories.some((c) => c.toLowerCase().includes(needle))
        );
      });
    }

    const total = items.length;
    const page = items.slice(offset, offset + limit);
    res.json({ items: page, total, limit, offset });
  } catch (err) {
    logger.error({ err }, "Failed to list episodes");
    res.status(502).json({ error: "Unable to load episodes" });
  }
});


router.get("/episodes/this-day", async (req, res) => {
  try {
    const now = new Date();
    const monthParam = req.query.month != null ? Number(req.query.month) : null;
    const dayParam = req.query.day != null ? Number(req.query.day) : null;

    const targetMonth = (monthParam != null && !Number.isNaN(monthParam))
      ? monthParam
      : now.getUTCMonth() + 1;
    const targetDay = (dayParam != null && !Number.isNaN(dayParam))
      ? dayParam
      : now.getUTCDate();

    // --- RSS feed: recent episodes ---
    const feed = await getFeedCached();
    const rssMatched = feed.episodes.filter((e) => {
      const d = new Date(e.pubDate);
      if (Number.isNaN(d.getTime())) return false;
      return d.getUTCMonth() + 1 === targetMonth && d.getUTCDate() === targetDay;
    });

    // Track slugs from RSS to deduplicate against DB results
    const rssSlugSet = new Set(rssMatched.map((e) => e.slug));
    const rssEpNumSet = new Set(
      rssMatched.map((e) => e.episodeNumber).filter((n): n is number => n != null),
    );

    // Collect RSS results with timestamp detection
    type ThisDayItem = {
      slug: string;
      guid: string;
      episodeNumber: number | null;
      title: string;
      link: string;
      pubDate: string;
      summary: string;
      durationSeconds: number | null;
      audioUrl: string | null;
      audioType: string | null;
      artworkUrl: string | null;
      categories: string[];
      historyTimestamp: number | null;
    };

    // For each RSS episode, try text detection first, then live chapter fetch
    const results: ThisDayItem[] = await Promise.all(
      rssMatched.map(async (e) => {
        const { descriptionHtml: _unused, ...summary } = e;
        let historyTimestamp = extractHistoryTimestamp(e.descriptionHtml);
        if (historyTimestamp === null && e.audioUrl) {
          try {
            const chapters = await fetchAudioChapters(e.audioUrl);
            historyTimestamp = extractChapterHistoryTimestamp(chapters);
          } catch (err) {
            logger.debug({ err, slug: e.slug }, "this-day: chapter fetch failed for RSS episode");
          }
        }
        return { ...summary, historyTimestamp };
      }),
    );

    // --- Library DB: full archive audio episodes ---
    try {
      const dbRows = await db
        .select()
        .from(contentItemsTable)
        .where(
          sql`${contentItemsTable.kind} = 'audio'
            AND extract_month_utc(${contentItemsTable.publishedAt}) = ${targetMonth}
            AND extract_day_utc(${contentItemsTable.publishedAt}) = ${targetDay}`,
        )
        .orderBy(sql`${contentItemsTable.publishedAt} DESC`);

      for (const row of dbRows) {
        // Skip if already covered by the RSS feed (same slug or episode number)
        if (rssSlugSet.has(row.slug)) continue;
        if (row.episodeNumber != null && rssEpNumSet.has(row.episodeNumber)) continue;

        // Prefer stored chapter timestamp (set at sync time), fall back to
        // text-based detection from show notes HTML
        const storedTs = (row.extra as Record<string, unknown> | null)
          ?.historyTimestamp;
        const historyTimestamp: number | null =
          typeof storedTs === "number"
            ? storedTs
            : row.bodyHtml
              ? extractHistoryTimestamp(row.bodyHtml)
              : null;

        results.push({
          slug: row.slug,
          guid: row.sourceId,
          episodeNumber: row.episodeNumber,
          title: row.title,
          link: row.link,
          pubDate: row.publishedAt.toISOString(),
          summary: row.summary,
          durationSeconds: row.durationSeconds,
          audioUrl: row.audioUrl,
          audioType: row.audioType,
          artworkUrl: row.artworkUrl,
          categories: row.categories,
          historyTimestamp,
        });
      }
    } catch (dbErr) {
      // DB may not be available (e.g. no sync yet); continue with RSS-only results
      logger.warn({ err: dbErr }, "this-day: DB query failed, serving RSS-only results");
    }

    // Sort all results by pubDate descending (newest year first)
    results.sort((a, b) => b.pubDate.localeCompare(a.pubDate));

    res.json(results);
  } catch (err) {
    logger.error({ err }, "Failed to load this-day episodes");
    res.status(502).json({ error: "Unable to load episodes" });
  }
});

router.get("/episodes/featured", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    const items = feed.episodes.slice(0, 5).map(toEpisodeSummary);
    res.json(items);
  } catch (err) {
    logger.error({ err }, "Failed to load featured episodes");
    res.status(502).json({ error: "Unable to load featured episodes" });
  }
});

router.get("/episodes/stats", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    const episodes = feed.episodes;
    const totalEpisodes = episodes.length;
    const latestPubDate = episodes[0]?.pubDate ?? null;
    const latestEpisodeNumber = episodes.find(
      (e) => e.episodeNumber != null,
    )?.episodeNumber ?? null;

    const durations = episodes
      .map((e) => e.durationSeconds)
      .filter((d): d is number => typeof d === "number" && d > 0);
    const averageDurationSeconds = durations.length
      ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length)
      : null;

    const cutoff = Date.now() - 30 * 24 * 60 * 60 * 1000;
    const episodesLast30Days = episodes.filter(
      (e) => new Date(e.pubDate).getTime() >= cutoff,
    ).length;

    const counts = new Map<string, number>();
    for (const e of episodes) {
      for (const c of e.categories) {
        counts.set(c, (counts.get(c) ?? 0) + 1);
      }
    }
    const topCategories = [...counts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([name, count]) => ({ name, count }));

    const monthCounts = new Map<string, number>();
    for (const e of episodes) {
      const d = new Date(e.pubDate);
      if (Number.isNaN(d.getTime())) continue;
      const key = `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
      monthCounts.set(key, (monthCounts.get(key) ?? 0) + 1);
    }
    const allKeys = [...monthCounts.keys()].sort();
    const last12 = allKeys.slice(-12);
    const publishHistogram = last12.map((month) => ({
      month,
      count: monthCounts.get(month) ?? 0,
    }));

    res.json({
      totalEpisodes,
      latestPubDate,
      latestEpisodeNumber,
      averageDurationSeconds,
      episodesLast30Days,
      topCategories,
      publishHistogram,
    });
  } catch (err) {
    logger.error({ err }, "Failed to load episode stats");
    res.status(502).json({ error: "Unable to load stats" });
  }
});

router.get("/categories", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    const autoDescs = getAutoGeneratedDescriptions();
    const counts = new Map<string, number>();
    for (const e of feed.episodes) {
      for (const c of e.categories) {
        counts.set(c, (counts.get(c) ?? 0) + 1);
      }
    }

    // Load all DB-managed descriptions once and build a lookup map (lowercase key)
    let dbDescriptions = new Map<string, string>();
    try {
      const rows = await db.select().from(categoryDescriptionsTable);
      for (const row of rows) {
        dbDescriptions.set(row.category.toLowerCase(), row.description);
      }
    } catch (dbErr) {
      logger.warn({ err: dbErr }, "categories: failed to load DB descriptions, falling back to static");
    }

    const list = [...counts.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([name, count]) => {
        const key = name.toLowerCase();
        // Priority: DB-managed > static curated > auto-generated from episode summary
        const dbDesc = dbDescriptions.get(key) ?? null;
        const curated = getCuratedDescription(name);
        const fallback = autoDescs.get(name) ?? null;
        const description = dbDesc ?? curated ?? fallback ?? undefined;
        return { name, count, description };
      });
    res.json(list);
  } catch (err) {
    logger.error({ err }, "Failed to list categories");
    res.status(502).json({ error: "Unable to load categories" });
  }
});

router.get("/episodes/:slug", async (req, res) => {
  try {
    const parsed = GetEpisodeParams.safeParse({ slug: req.params.slug });
    if (!parsed.success) {
      res.status(400).json({ error: "Invalid slug" });
      return;
    }
    const { slug } = parsed.data;
    const feed = await getFeedCached();

    let ep: RssEpisode | undefined = feed.episodes.find((e) => e.slug === slug);

    // Fall back to library DB for older episodes not in the RSS window
    if (!ep) {
      try {
        const rows = await db
          .select()
          .from(contentItemsTable)
          .where(
            and(
              sql`${contentItemsTable.kind} = 'audio'`,
              sql`${contentItemsTable.slug} = ${slug}`,
            ),
          )
          .limit(1);
        if (rows[0]) {
          ep = libraryRowToRssEpisode(rows[0]);
        }
      } catch (dbErr) {
        logger.warn({ err: dbErr, slug }, "episodes/:slug — DB fallback failed");
      }
    }

    if (!ep) {
      res.status(404).json({ error: "Episode not found" });
      return;
    }

    const { seriesSlug, positionInSeries } = await getEpisodeSeriesContext(ep, feed.episodes);

    res.json({ ...ep, seriesSlug, positionInSeries });
  } catch (err) {
    logger.error({ err }, "Failed to load episode");
    res.status(502).json({ error: "Unable to load episode" });
  }
});

export default router;
