import { Router, type IRouter } from "express";
import {
  ListEpisodesQueryParams,
  GetEpisodeParams,
} from "@workspace/api-zod";
import { zoneBySlug } from "../lib/zones";
import { getFeedCached, getAutoGeneratedDescriptions, getAutoDescriptionMetadata, type RssEpisode } from "../lib/rss";
import { logger } from "../lib/logger";
import { extractHistoryTimestamp, extractHistorySegment, type HistorySegmentData } from "../lib/history-detection";
import { fetchAudioChapters, extractChapterHistoryTimestamp } from "../lib/id3-chapters";
import { enrichHistoryEpisode, type HistoryCrossLink } from "../lib/history-enrichment";
import { sql, or, and, eq } from "drizzle-orm";
import { db, contentItemsTable, categoryDescriptionsTable } from "@workspace/db";
import {
  getEpisodeSeriesContext,
  libraryRowToRssEpisode,
} from "../lib/series";

const router: IRouter = Router();

const TAG_CACHE_TTL_MS = 5 * 60 * 1000;

type TagCacheEntry = {
  fetchedAt: number;
  items: EpisodeSummary[];
};

const tagQueryCache = new Map<string, TagCacheEntry>();

function tagCacheKey(normalizedTags: string[], sort: string): string {
  return [...normalizedTags].sort().join("|") + ":" + sort;
}

type SortOrder = "newest" | "oldest" | "popular";

/**
 * Returns a comparator for EpisodeSummary items.
 *
 * - newest  : most recent pubDate first (default / fallback)
 * - oldest  : oldest pubDate first
 * - popular : lowest episode number first (foundational / evergreen episodes);
 *             episodes without a number sort after numbered ones, then by pubDate asc.
 *             Falls back to recency when no episodeNumber is available.
 */
function sortComparator(sort: SortOrder | string | undefined): (a: EpisodeSummary, b: EpisodeSummary) => number {
  if (sort === "oldest") {
    return (a, b) => a.pubDate.localeCompare(b.pubDate);
  }
  if (sort === "popular") {
    return (a, b) => {
      const aNum = a.episodeNumber ?? null;
      const bNum = b.episodeNumber ?? null;
      // Both have episode numbers: lower number = more foundational
      if (aNum !== null && bNum !== null) return aNum - bNum;
      // Only a has a number: a comes first
      if (aNum !== null) return -1;
      // Only b has a number: b comes first
      if (bNum !== null) return 1;
      // Neither has a number: fall back to oldest-first
      return a.pubDate.localeCompare(b.pubDate);
    };
  }
  // newest (default)
  return (a, b) => b.pubDate.localeCompare(a.pubDate);
}

export function invalidateTagQueryCache(): void {
  tagQueryCache.clear();
  logger.info("Tag query cache invalidated");
}

function toEpisodeSummary(e: RssEpisode) {
  const { descriptionHtml: _unused, ...rest } = e;
  return rest;
}

router.get("/feed", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    res.json({
      title: feed.title,
      description: feed.description,
      link: feed.link,
      host: feed.host,
      artworkUrl: feed.artworkUrl,
      copyright: feed.copyright,
      language: feed.language,
      totalEpisodes: feed.totalEpisodes,
      latestPubDate: feed.latestPubDate,
      tipUrl: feed.tipUrl,
    });
  } catch (err) {
    logger.error({ err }, "Failed to load feed");
    res.status(502).json({ error: "Unable to load podcast feed" });
  }
});

type EpisodeSummary = Omit<RssEpisode, "descriptionHtml">;

router.get("/episodes", async (req, res) => {
  try {
    const rawTags = req.query["tags[]"] ?? req.query.tags;
    const tagsInput: string[] = Array.isArray(rawTags)
      ? (rawTags as string[])
      : typeof rawTags === "string"
        ? [rawTags]
        : [];

    const parsed = ListEpisodesQueryParams.safeParse({
      limit: req.query.limit != null ? Number(req.query.limit) : undefined,
      offset: req.query.offset != null ? Number(req.query.offset) : undefined,
      q: typeof req.query.q === "string" ? req.query.q : undefined,
      category:
        typeof req.query.category === "string" ? req.query.category : undefined,
      tags: tagsInput.length > 0 ? tagsInput : undefined,
      sort: typeof req.query.sort === "string" ? req.query.sort : undefined,
      hasHistory: req.query.hasHistory != null ? req.query.hasHistory : undefined,
      zone: typeof req.query.zone === "string" ? req.query.zone : undefined,
    });
    if (!parsed.success) {
      res.status(400).json({ error: "Invalid query parameters" });
      return;
    }
    const { limit = 20, offset = 0, q, category, sort = "newest", hasHistory, zone } = parsed.data;
    let { tags } = parsed.data;

    // ── Zone filter: expand zone slug into its tag list ─────────────────────
    if (zone) {
      const zoneDef = zoneBySlug(zone);
      if (zoneDef) {
        const zoneTerms = [...new Set([...zoneDef.tags, ...zoneDef.categories])];
        tags = tags ? [...new Set([...tags, ...zoneTerms])] : zoneTerms;
      }
    }

    // ── hasHistory filter: find episodes with a detectable history segment ────
    // Resolved before feed fetch to avoid the 1-2s RSS wait on the /history page.
    if (hasHistory) {
      try {
        // Primary query: fast JSON-index lookup for episodes where detection has
        // already been run and persisted.  Covers 100 % of known history episodes
        // after the first request triggers the fire-and-forget persist path.
        let candidates = await db
          .select()
          .from(contentItemsTable)
          .where(
            and(
              sql`${contentItemsTable.kind} = 'audio'`,
              sql`(${contentItemsTable.extra}->>'historyTimestamp') IS NOT NULL`,
            ),
          )
          .orderBy(sql`${contentItemsTable.publishedAt} DESC`);

        // Fallback (first-run / new episodes): ILIKE keyword scan to discover
        // candidates that haven't been detected yet, then persist so next request
        // is instant.  Only executed when the JSON set is empty.
        if (candidates.length === 0) {
          candidates = await db
            .select()
            .from(contentItemsTable)
            .where(
              and(
                sql`${contentItemsTable.kind} = 'audio'`,
                or(
                  sql`${contentItemsTable.bodyHtml} ILIKE '%this day in history%'`,
                  sql`${contentItemsTable.bodyHtml} ILIKE '%today in history%'`,
                  sql`${contentItemsTable.bodyHtml} ILIKE '%on this date%'`,
                  sql`${contentItemsTable.bodyHtml} ILIKE '%tsp history%'`,
                  sql`${contentItemsTable.bodyHtml} ILIKE '%history segment%'`,
                  sql`${contentItemsTable.bodyHtml} ILIKE '%history with jack%'`,
                  sql`${contentItemsTable.bodyHtml} ILIKE '%in history today%'`,
                ),
              ),
            )
            .orderBy(sql`${contentItemsTable.publishedAt} DESC`);
        }

        type HistoryItem = EpisodeSummary & { historySegment: HistorySegmentData | null };
        const historyItems: HistoryItem[] = [];

        for (const row of candidates) {
          const extra = (row.extra as Record<string, unknown>) ?? {};

          // Fast path: all three values already stored
          const storedStart = typeof extra.historyTimestamp === "number" ? extra.historyTimestamp : null;
          const storedEnd = typeof extra.historyEndTimestamp === "number" ? extra.historyEndTimestamp : null;
          const storedText = typeof extra.historyText === "string" ? extra.historyText : null;

          let historySegment: HistorySegmentData | null = null;
          if (storedStart !== null && storedEnd !== null && storedText !== null) {
            historySegment = { startSeconds: storedStart, endSeconds: storedEnd, lessonText: storedText };
          } else if (row.bodyHtml) {
            historySegment = extractHistorySegment(row.bodyHtml);
            if (historySegment) {
              // Persist for fast subsequent loads (fire-and-forget)
              db.update(contentItemsTable)
                .set({
                  extra: {
                    ...extra,
                    historyTimestamp: historySegment.startSeconds,
                    historyEndTimestamp: historySegment.endSeconds,
                    historyText: historySegment.lessonText,
                  },
                })
                .where(eq(contentItemsTable.id, row.id))
                .catch(() => {});
            }
          } else if (storedStart !== null) {
            // Legacy: start stored but no end/text
            historySegment = { startSeconds: storedStart, endSeconds: storedStart + 480, lessonText: "" };
          }

          if (!historySegment) continue;

          historyItems.push({
            slug: row.slug,
            guid: row.sourceId,
            episodeNumber: row.episodeNumber,
            title: row.title,
            link: row.link,
            pubDate: row.publishedAt.toISOString(),
            summary: row.summary ?? "",
            durationSeconds: row.durationSeconds,
            audioUrl: row.audioUrl,
            audioType: row.audioType,
            artworkUrl: row.artworkUrl,
            categories: row.categories ?? [],
            tags: row.tags ?? [],
            chaptersJsonUrl: null,
            historySegment,
          });
        }

        let filtered = historyItems as HistoryItem[];
        if (q && q.trim()) {
          const needle = q.trim().toLowerCase();
          filtered = historyItems.filter(
            (e) =>
              e.title.toLowerCase().includes(needle) ||
              (e.summary ?? "").toLowerCase().includes(needle) ||
              (e.historySegment?.lessonText ?? "").toLowerCase().includes(needle),
          );
        }

        const total = filtered.length;
        const page = filtered.slice(offset, offset + limit);
        res.json({ items: page, total, limit, offset });
        return;
      } catch (dbErr) {
        logger.warn({ err: dbErr }, "episodes: hasHistory query failed");
        res.status(502).json({ error: "Unable to load history episodes" });
        return;
      }
    }

    // RSS feed is only needed for the normal listing path (not hasHistory)
    const feed = await getFeedCached();

    // Apply tag / category filter on RSS episodes, then strip descriptionHtml
    let rssItems = feed.episodes;
    if (tags && tags.length > 0) {
      const normalizedTags = tags.map((t) => t.toLowerCase());
      rssItems = rssItems.filter((e) =>
        e.categories.some((c) => normalizedTags.includes(c.toLowerCase())),
      );
    } else if (category) {
      const cat = category.toLowerCase();
      rssItems = rssItems.filter((e) =>
        e.categories.some((c) => c.toLowerCase() === cat),
      );
    }

    let items: EpisodeSummary[] = rssItems.map(toEpisodeSummary);

    // When a tags filter is active, also pull matching episodes from the full
    // DB library (3 800+ episodes) so historical content is included.
    // Results are cached in-memory for TAG_CACHE_TTL_MS to avoid repeated
    // heavy JSONB queries on every page change.
    if (tags && tags.length > 0) {
      const normalizedTags = tags.map((t) => t.toLowerCase());
      const cacheKey = tagCacheKey(normalizedTags, sort ?? "newest");
      const now = Date.now();
      const cached = tagQueryCache.get(cacheKey);

      if (cached && now - cached.fetchedAt < TAG_CACHE_TTL_MS) {
        items = cached.items;
        logger.debug({ cacheKey }, "episodes: serving merged tag results from cache");
      } else {
        try {
          // Match any audio item whose `tags` OR `categories` JSONB column
          // contains at least one of the requested tag values.
          // Uses the proven `@>` containment operator (same as library.ts search).
          // One condition per tag, all OR'd together for both columns.
          const tagOrConditions = normalizedTags.flatMap((tag) => [
            sql`${contentItemsTable.tags} @> ${JSON.stringify([tag])}::jsonb`,
            sql`${contentItemsTable.categories} @> ${JSON.stringify([tag])}::jsonb`,
          ]);
          const dbRows = await db
            .select()
            .from(contentItemsTable)
            .where(
              and(
                sql`${contentItemsTable.kind} = 'audio'`,
                or(...tagOrConditions),
              ),
            )
            .orderBy(sql`${contentItemsTable.publishedAt} DESC`)
            .limit(2000);

          // Deduplicate against what RSS already returned
          const rssSlugSet = new Set(items.map((e) => e.slug));
          const rssEpNumSet = new Set(
            items
              .map((e) => e.episodeNumber)
              .filter((n): n is number => n != null),
          );

          for (const row of dbRows) {
            if (rssSlugSet.has(row.slug)) continue;
            if (row.episodeNumber != null && rssEpNumSet.has(row.episodeNumber))
              continue;

            items.push({
              slug: row.slug,
              guid: row.sourceId,
              episodeNumber: row.episodeNumber,
              title: row.title,
              link: row.link,
              pubDate: row.publishedAt.toISOString(),
              summary: row.summary,
              durationSeconds: row.durationSeconds,
              audioUrl: row.audioUrl,
              audioType: row.audioType,
              artworkUrl: row.artworkUrl,
              categories: row.categories,
              tags: row.tags ?? [],
              chaptersJsonUrl: null,
            });
          }

          // Sort the merged list according to requested order
          items.sort(sortComparator(sort));

          tagQueryCache.set(cacheKey, { fetchedAt: now, items });
          logger.debug({ cacheKey, total: items.length }, "episodes: tag query result cached");
        } catch (dbErr) {
          logger.warn(
            { err: dbErr },
            "episodes: DB tags query failed, serving RSS-only results",
          );
        }
      }
    }

    // Apply sort to RSS-only paths (tags path sorts internally; this covers
    // category-only or no-filter requests whose items come pre-sorted newest-first
    // from the RSS feed and may need re-ordering for oldest/popular).
    if (!tags || tags.length === 0) {
      items.sort(sortComparator(sort));
    }

    if (q && q.trim()) {
      const needle = q.trim().toLowerCase();
      items = items.filter((e) => {
        return (
          e.title.toLowerCase().includes(needle) ||
          e.summary.toLowerCase().includes(needle) ||
          e.categories.some((c) => c.toLowerCase().includes(needle))
        );
      });
    }

    const total = items.length;
    const page = items.slice(offset, offset + limit);
    res.json({ items: page, total, limit, offset });
  } catch (err) {
    logger.error({ err }, "Failed to list episodes");
    res.status(502).json({ error: "Unable to load episodes" });
  }
});


router.get("/episodes/this-day", async (req, res) => {
  try {
    const now = new Date();
    const monthParam = req.query.month != null ? Number(req.query.month) : null;
    const dayParam = req.query.day != null ? Number(req.query.day) : null;

    const targetMonth = (monthParam != null && !Number.isNaN(monthParam))
      ? monthParam
      : now.getUTCMonth() + 1;
    const targetDay = (dayParam != null && !Number.isNaN(dayParam))
      ? dayParam
      : now.getUTCDate();

    // --- RSS feed: recent episodes ---
    const feed = await getFeedCached();
    const rssMatched = feed.episodes.filter((e) => {
      const d = new Date(e.pubDate);
      if (Number.isNaN(d.getTime())) return false;
      return d.getUTCMonth() + 1 === targetMonth && d.getUTCDate() === targetDay;
    });

    // Track slugs from RSS to deduplicate against DB results
    const rssSlugSet = new Set(rssMatched.map((e) => e.slug));
    const rssEpNumSet = new Set(
      rssMatched.map((e) => e.episodeNumber).filter((n): n is number => n != null),
    );

    // Collect RSS results with timestamp detection
    type ThisDayItem = {
      slug: string;
      guid: string;
      episodeNumber: number | null;
      title: string;
      link: string;
      pubDate: string;
      summary: string;
      durationSeconds: number | null;
      audioUrl: string | null;
      audioType: string | null;
      artworkUrl: string | null;
      categories: string[];
      tags: string[];
      historyTimestamp: number | null;
      historySegment: HistorySegmentData | null;
      _descriptionHtml?: string | null;
      _precomputedUlg?: HistoryCrossLink | null;
      _precomputedExpert?: HistoryCrossLink | null;
    };

    // For each RSS episode, try text detection first, then live chapter fetch
    const results: ThisDayItem[] = await Promise.all(
      rssMatched.map(async (e) => {
        const { descriptionHtml, ...summary } = e;
        let historyTimestamp = extractHistoryTimestamp(descriptionHtml);
        let historySegment = extractHistorySegment(descriptionHtml);
        if (historyTimestamp === null && e.audioUrl) {
          try {
            const chapters = await fetchAudioChapters(e.audioUrl);
            historyTimestamp = extractChapterHistoryTimestamp(chapters);
            if (historyTimestamp !== null && historySegment === null) {
              historySegment = { startSeconds: historyTimestamp, endSeconds: historyTimestamp + 480, lessonText: "" };
            }
          } catch (err) {
            logger.debug({ err, slug: e.slug }, "this-day: chapter fetch failed for RSS episode");
          }
        }
        return { ...summary, historyTimestamp, historySegment, _descriptionHtml: descriptionHtml };
      }),
    );

    // --- Library DB: full archive audio episodes ---
    try {
      const dbRows = await db
        .select()
        .from(contentItemsTable)
        .where(
          sql`${contentItemsTable.kind} = 'audio'
            AND extract_month_utc(${contentItemsTable.publishedAt}) = ${targetMonth}
            AND extract_day_utc(${contentItemsTable.publishedAt}) = ${targetDay}`,
        )
        .orderBy(sql`${contentItemsTable.publishedAt} DESC`);

      for (const row of dbRows) {
        // Skip if already covered by the RSS feed (same slug or episode number)
        if (rssSlugSet.has(row.slug)) continue;
        if (row.episodeNumber != null && rssEpNumSet.has(row.episodeNumber)) continue;

        // Prefer stored chapter timestamp (set at sync time), fall back to
        // text-based detection from show notes HTML
        const extra = (row.extra as Record<string, unknown> | null) ?? {};
        const storedTs = extra.historyTimestamp;
        const storedEnd = typeof extra.historyEndTimestamp === "number" ? extra.historyEndTimestamp : null;
        const storedText = typeof extra.historyText === "string" ? extra.historyText : null;

        let historyTimestamp: number | null = typeof storedTs === "number"
          ? storedTs
          : row.bodyHtml
            ? extractHistoryTimestamp(row.bodyHtml)
            : null;

        let historySegment: HistorySegmentData | null = null;
        if (historyTimestamp !== null) {
          if (storedEnd !== null && storedText !== null) {
            historySegment = { startSeconds: historyTimestamp, endSeconds: storedEnd, lessonText: storedText };
          } else if (row.bodyHtml) {
            historySegment = extractHistorySegment(row.bodyHtml);
          }
          if (!historySegment) {
            historySegment = { startSeconds: historyTimestamp, endSeconds: historyTimestamp + 480, lessonText: "" };
          }
        }

        // Extract pre-computed cross-links stored at sync time
        const ulgStored = extra.ulgCrossLink;
        const expertStored = extra.expertLink;
        const precomputedUlg = (ulgStored !== undefined)
          ? (ulgStored as HistoryCrossLink | null)
          : undefined;
        const precomputedExpert = (expertStored !== undefined)
          ? (expertStored as HistoryCrossLink | null)
          : undefined;

        results.push({
          slug: row.slug,
          guid: row.sourceId,
          episodeNumber: row.episodeNumber,
          title: row.title,
          link: row.link,
          pubDate: row.publishedAt.toISOString(),
          summary: row.summary,
          durationSeconds: row.durationSeconds,
          audioUrl: row.audioUrl,
          audioType: row.audioType,
          artworkUrl: row.artworkUrl,
          categories: row.categories,
          tags: row.tags ?? [],
          historyTimestamp,
          historySegment,
          _descriptionHtml: row.bodyHtml,
          _precomputedUlg: precomputedUlg,
          _precomputedExpert: precomputedExpert,
        });
      }
    } catch (dbErr) {
      // DB may not be available (e.g. no sync yet); continue with RSS-only results
      logger.warn({ err: dbErr }, "this-day: DB query failed, serving RSS-only results");
    }

    // Sort all results by pubDate descending (newest year first)
    results.sort((a, b) => b.pubDate.localeCompare(a.pubDate));

    // Enrich each episode in parallel (cached per slug, so fast on repeat requests).
    // For DB episodes, pre-computed ULG/expert cross-links are passed in so the
    // enrichment skips the live DB round-trips for those fields.
    const enriched = await Promise.all(
      results.map(async (item) => {
        const { _descriptionHtml, _precomputedUlg, _precomputedExpert, ...rest } = item;
        try {
          const precomputed =
            _precomputedUlg !== undefined || _precomputedExpert !== undefined
              ? { ulgCrossLink: _precomputedUlg, expertLink: _precomputedExpert }
              : undefined;
          const enrichment = await enrichHistoryEpisode(
            item.slug,
            item.title,
            _descriptionHtml ?? null,
            item.summary,
            precomputed,
          );
          return { ...rest, ...enrichment };
        } catch (err) {
          logger.debug({ err, slug: item.slug }, "this-day: enrichment failed");
          return {
            ...rest,
            historyImageUrl: null,
            lessonQuote: null,
            bulletPoints: [],
            sourceLinks: [],
          };
        }
      }),
    );

    res.json(enriched);
  } catch (err) {
    logger.error({ err }, "Failed to load this-day episodes");
    res.status(502).json({ error: "Unable to load episodes" });
  }
});

router.get("/episodes/featured", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    const items = feed.episodes.slice(0, 5).map(toEpisodeSummary);
    res.json(items);
  } catch (err) {
    logger.error({ err }, "Failed to load featured episodes");
    res.status(502).json({ error: "Unable to load featured episodes" });
  }
});

router.get("/episodes/stats", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    const episodes = feed.episodes;
    const totalEpisodes = episodes.length;
    const latestPubDate = episodes[0]?.pubDate ?? null;
    const latestEpisodeNumber = episodes.find(
      (e) => e.episodeNumber != null,
    )?.episodeNumber ?? null;

    const durations = episodes
      .map((e) => e.durationSeconds)
      .filter((d): d is number => typeof d === "number" && d > 0);
    const averageDurationSeconds = durations.length
      ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length)
      : null;

    const cutoff = Date.now() - 30 * 24 * 60 * 60 * 1000;
    const episodesLast30Days = episodes.filter(
      (e) => new Date(e.pubDate).getTime() >= cutoff,
    ).length;

    const counts = new Map<string, number>();
    for (const e of episodes) {
      for (const c of e.categories) {
        counts.set(c, (counts.get(c) ?? 0) + 1);
      }
    }
    const topCategories = [...counts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([name, count]) => ({ name, count }));

    const monthCounts = new Map<string, number>();
    for (const e of episodes) {
      const d = new Date(e.pubDate);
      if (Number.isNaN(d.getTime())) continue;
      const key = `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
      monthCounts.set(key, (monthCounts.get(key) ?? 0) + 1);
    }
    const allKeys = [...monthCounts.keys()].sort();
    const last12 = allKeys.slice(-12);
    const publishHistogram = last12.map((month) => ({
      month,
      count: monthCounts.get(month) ?? 0,
    }));

    res.json({
      totalEpisodes,
      latestPubDate,
      latestEpisodeNumber,
      averageDurationSeconds,
      episodesLast30Days,
      topCategories,
      publishHistogram,
    });
  } catch (err) {
    logger.error({ err }, "Failed to load episode stats");
    res.status(502).json({ error: "Unable to load stats" });
  }
});

const AUTO_DESC_STALE_MS = 7 * 24 * 60 * 60 * 1000;

router.get("/categories", async (_req, res) => {
  try {
    const feed = await getFeedCached();
    const autoDescs = getAutoGeneratedDescriptions();
    const autoMeta = getAutoDescriptionMetadata();
    const counts = new Map<string, number>();
    for (const e of feed.episodes) {
      for (const c of e.categories) {
        counts.set(c, (counts.get(c) ?? 0) + 1);
      }
    }

    // Load all DB-managed descriptions once and build a lookup map (lowercase key)
    let dbDescriptions = new Map<string, { description: string; updatedAt: Date }>();
    try {
      const rows = await db.select().from(categoryDescriptionsTable);
      for (const row of rows) {
        dbDescriptions.set(row.category.toLowerCase(), {
          description: row.description,
          updatedAt: row.updatedAt,
        });
      }
    } catch (dbErr) {
      logger.warn({ err: dbErr }, "categories: failed to load DB descriptions, falling back to auto-generated");
    }

    const now = Date.now();
    const list = [...counts.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([name, count]) => {
        const key = name.toLowerCase();
        // Priority: DB-managed > auto-generated from episode summary
        // Curated descriptions live solely in the DB (seeded from seed-category-descriptions.ts).
        const dbEntry = dbDescriptions.get(key) ?? null;
        const fallback = autoDescs.get(name) ?? null;
        const description = dbEntry?.description ?? fallback ?? undefined;

        // autoDescriptionStale: true when no DB description exists and the
        // auto-description's source episode is older than 7 days.
        const hasCurated = dbEntry !== null;
        const autoEntry = autoMeta.get(name);
        const autoDescriptionStale =
          !hasCurated &&
          autoEntry !== undefined &&
          now - new Date(autoEntry.latestPubDate).getTime() > AUTO_DESC_STALE_MS;

        // descriptionUpdatedAt: DB row's updatedAt, or auto-desc's latestPubDate, or null
        let descriptionUpdatedAt: string | null = null;
        if (dbEntry) {
          descriptionUpdatedAt = dbEntry.updatedAt.toISOString();
        } else if (autoEntry !== undefined) {
          descriptionUpdatedAt = autoEntry.latestPubDate;
        }

        return { name, count, description, autoDescriptionStale, descriptionUpdatedAt };
      });
    res.json(list);
  } catch (err) {
    logger.error({ err }, "Failed to list categories");
    res.status(502).json({ error: "Unable to load categories" });
  }
});

router.get("/episodes/:slug", async (req, res) => {
  try {
    const parsed = GetEpisodeParams.safeParse({ slug: req.params.slug });
    if (!parsed.success) {
      res.status(400).json({ error: "Invalid slug" });
      return;
    }
    const { slug } = parsed.data;
    const feed = await getFeedCached();

    let ep: RssEpisode | undefined = feed.episodes.find((e) => e.slug === slug);

    // Fall back to library DB for older episodes not in the RSS window
    if (!ep) {
      try {
        const rows = await db
          .select()
          .from(contentItemsTable)
          .where(
            and(
              sql`${contentItemsTable.kind} = 'audio'`,
              sql`${contentItemsTable.slug} = ${slug}`,
            ),
          )
          .limit(1);
        if (rows[0]) {
          ep = libraryRowToRssEpisode(rows[0]);
        }
      } catch (dbErr) {
        logger.warn({ err: dbErr, slug }, "episodes/:slug — DB fallback failed");
      }
    }

    if (!ep) {
      res.status(404).json({ error: "Episode not found" });
      return;
    }

    const { seriesSlug, positionInSeries } = await getEpisodeSeriesContext(ep, feed.episodes);

    // Compute history segment from show notes
    const historySegment = ep.descriptionHtml
      ? extractHistorySegment(ep.descriptionHtml)
      : null;

    res.json({ ...ep, seriesSlug, positionInSeries, historySegment });
  } catch (err) {
    logger.error({ err }, "Failed to load episode");
    res.status(502).json({ error: "Unable to load episode" });
  }
});

export default router;
