import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import episodesRouter from "./episodes";
import libraryRouter from "./library";
import seriesRouter from "./series";
import zonesRouter from "./zones";
import expertsRouter from "./experts";
import tracksRouter from "./tracks";
import transformationsRouter from "./transformations";
import trackProgressRouter from "./track-progress";
import wishingWellRouter from "./wishing-well";
import v4vRouter from "./v4v";
import ogRouter from "./og";
import gapsRouter from "./gaps";
import wisdomRouter from "./wisdom";
import adminWisdomRouter from "./admin-wisdom";
import gearRouter from "./gear";
import waterWheelRouter from "./water-wheel";
import adminNuggetsRouter from "./admin-nuggets";
import adminCategoriesRouter from "./admin-categories";
import adminCouncilRouter from "./admin-council";
import groundEventsRouter from "./ground-events";
import adminGroundEventsRouter from "./admin-ground-events";
import stripeWorkshopsRouter from "./stripe-workshops";
import debtCoachRouter from "./debt-coach";
import fieldNotesRouter from "./field-notes";
import adminFieldNotesRouter from "./admin-field-notes";
import adminSyncStatusRouter from "./admin-sync-status";
import mapRouter from "./map";
import codetryAssessRouter from "./codetry-assess";
import headwatersRouter from "./headwaters";
import firesideChatsRouter from "./fireside-chats";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(episodesRouter);
router.use(libraryRouter);
router.use(seriesRouter);
router.use(zonesRouter);
router.use(expertsRouter);
router.use(tracksRouter);
router.use(transformationsRouter);
router.use(gapsRouter);
router.use(gearRouter);
router.use(trackProgressRouter);
router.use(wishingWellRouter);
router.use(v4vRouter);
router.use(ogRouter);
router.use(wisdomRouter);
router.use(groundEventsRouter);
router.use(waterWheelRouter);
router.use(debtCoachRouter);
router.use(fieldNotesRouter);
router.use(adminWisdomRouter);
router.use(adminNuggetsRouter);
router.use(adminCategoriesRouter);
router.use(adminCouncilRouter);
router.use(adminGroundEventsRouter);
router.use(stripeWorkshopsRouter);
router.use(adminFieldNotesRouter);
router.use(adminSyncStatusRouter);
router.use(mapRouter);
router.use(codetryAssessRouter);
router.use(headwatersRouter);
router.use(firesideChatsRouter);

export default router;
