import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import episodesRouter from "./episodes";
import libraryRouter from "./library";
import seriesRouter from "./series";
import zonesRouter from "./zones";
import expertsRouter from "./experts";
import tracksRouter from "./tracks";
import transformationsRouter from "./transformations";
import trackProgressRouter from "./track-progress";
import wishingWellRouter from "./wishing-well";
import v4vRouter from "./v4v";
import ogRouter from "./og";
import gapsRouter from "./gaps";
import wisdomRouter from "./wisdom";
import adminWisdomRouter from "./admin-wisdom";
import gearRouter from "./gear";
import waterWheelRouter from "./water-wheel";
import adminNuggetsRouter from "./admin-nuggets";
import adminCategoriesRouter from "./admin-categories";
import adminCouncilRouter from "./admin-council";
import groundEventsRouter from "./ground-events";
import adminGroundEventsRouter from "./admin-ground-events";
import stripeWorkshopsRouter from "./stripe-workshops";
import debtCoachRouter from "./debt-coach";
import fieldNotesRouter from "./field-notes";
import adminFieldNotesRouter from "./admin-field-notes";
import adminSyncStatusRouter from "./admin-sync-status";
import mapRouter from "./map";
import codetryAssessRouter from "./codetry-assess";
import headwatersRouter from "./headwaters";
import firesideChatsRouter from "./fireside-chats";
import brigadeRouter from "./brigade";
import expertListingsRouter from "./expert-listings";
import adminExpertListingsRouter from "./admin-expert-listings";
import cohortsRouter from "./cohorts";
import adminCohortsRouter from "./admin-cohorts";
import adminXrpRateRouter from "./admin-xrp-rate";
import kitsRouter from "./kits";
import suiteRouter from "./suite";
import adminKitPurchasesRouter from "./admin-kit-purchases";
import adminGordTipsRouter from "./admin-gord-tips";
import practitionersRouter from "./practitioners";
import trailblazerRouter from "./trailblazer";
import gordRouter from "./gord";
import stompingPathRouter from "./stomping-path";
import suggestionsRouter from "./suggestions";
import sharesRouter from "./shares";
import storageFilesRouter from "./storage-files";
import adminArtworkBackfillRouter from "./admin-artwork-backfill";
import adminKitExpiryRemindersRouter from "./admin-kit-expiry-reminders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(episodesRouter);
router.use(libraryRouter);
router.use(seriesRouter);
router.use(zonesRouter);
router.use(expertsRouter);
router.use(tracksRouter);
router.use(transformationsRouter);
router.use(gapsRouter);
router.use(gearRouter);
router.use(brigadeRouter);
router.use(trackProgressRouter);
router.use(wishingWellRouter);
router.use(v4vRouter);
router.use(ogRouter);
router.use(wisdomRouter);
router.use(groundEventsRouter);
router.use(waterWheelRouter);
router.use(debtCoachRouter);
router.use(fieldNotesRouter);
router.use(codetryAssessRouter);
router.use(adminWisdomRouter);
router.use(adminNuggetsRouter);
router.use(adminCategoriesRouter);
router.use(adminCouncilRouter);
router.use(adminGroundEventsRouter);
router.use(stripeWorkshopsRouter);
router.use(adminFieldNotesRouter);
router.use(adminSyncStatusRouter);
router.use(mapRouter);
router.use(headwatersRouter);
router.use(firesideChatsRouter);
router.use(expertListingsRouter);
router.use(adminExpertListingsRouter);
router.use(cohortsRouter);
router.use(adminCohortsRouter);
router.use(adminXrpRateRouter);
router.use(kitsRouter);
router.use(suiteRouter);
router.use(adminKitPurchasesRouter);
router.use(adminGordTipsRouter);
router.use(practitionersRouter);
router.use(trailblazerRouter);
router.use(gordRouter);
router.use(stompingPathRouter);
router.use(suggestionsRouter);
router.use(sharesRouter);
router.use(storageFilesRouter);
router.use(adminArtworkBackfillRouter);
router.use(adminKitExpiryRemindersRouter);

export default router;
